export default dataCourses=[
    {
        image:require('../Assets/image/flame.png'),
        title:'طراحی آبستره',
        text:'طراح گرافیک از این متن به عنوان عنصری از ترکیب بندی برای پر کردن صفحه و ارایه اولیه شکل ظاهری و کلی طرح سفارش گرفته شده استفاده می نماید، تا از نظر گرافیکی نشانگر چگونگی نوع و اندازه فونت و ظاهر متن باشد.',
        percentage:76,
        one:require('../Assets/image/1.jpg'),
        two:require('../Assets/image/2.jpg'),
        three:require('../Assets/image/3.jpg'),
        four:require('../Assets/image/4.jpg'),
    },
    {
        image:require('../Assets/image/sky.png'),
        title:'طراحی صنعتی',
        text:'معمولا طراحان گرافیک برای صفحه‌آرایی، نخست از متن‌های آزمایشی و بی‌معنی استفاده می‌کنند تا صرفا به مشتری یا صاحب کار خود نشان دهند که صفحه طراحی یا صفحه بندی شده بعد از اینکه متن در آن قرار گیرد چگونه به نظر می‌رسد و قلم‌ها و اندازه‌بندی‌ها چگونه در نظر گرفته شده‌است.',
        percentage:32,
        one:require('../Assets/image/5.jpg'),
        two:require('../Assets/image/6.jpg'),
        three:require('../Assets/image/7.jpg'),
        four:require('../Assets/image/8.jpg'),
    },
    {
        image:require('../Assets/image/lens.png'),
        title:'عکاسی',
        text:'از آنجایی که طراحان عموما نویسنده متن نیستند و وظیفه رعایت حق تکثیر متون را ندارند و در همان حال کار آنها به نوعی وابسته به متن می‌باشد آنها با استفاده از محتویات ساختگی، صفحه گرافیکی خود را صفحه‌آرایی می‌کنند تا مرحله طراحی و صفحه‌بندی را به پایان برند.',
        percentage:46,
        one:require('../Assets/image/9.jpg'),
        two:require('../Assets/image/10.jpg'),
        three:require('../Assets/image/11.jpg'),
        four:require('../Assets/image/12.jpg'),
    },
    {
        image:require('../Assets/image/charts.png'),
        title:'بازاریابی و مالی',
        text:'لورم ایپسوم یا طرح‌نما (به انگلیسی: Lorem ipsum) به متنی آزمایشی و بی‌معنی در صنعت چاپ، صفحه‌آرایی و طراحی گرافیک گفته می‌شود. طراح گرافیک از این متن به عنوان عنصری از ترکیب بندی برای پر کردن صفحه و ارایه اولیه شکل ظاهری و کلی طرح سفارش گرفته شده استفاده می نماید، تا از نظر گرافیکی نشانگر چگونگی نوع و اندازه فونت و ظاهر متن باشد.',
        percentage:12,
        one:require('../Assets/image/1.jpg'),
        two:require('../Assets/image/2.jpg'),
        three:require('../Assets/image/3.jpg'),
        four:require('../Assets/image/4.jpg'),
    },
    {
        image:require('../Assets/image/ice.png'),
        title:'هنر های سه بعدی',
        text:'از آنجایی که طراحان عموما نویسنده متن نیستند و وظیفه رعایت حق تکثیر متون را ندارند و در همان حال کار آنها به نوعی وابسته به متن می‌باشد آنها با استفاده از محتویات ساختگی، صفحه گرافیکی خود را صفحه‌آرایی می‌کنند تا مرحله طراحی و صفحه‌بندی را به پایان برند.',
        percentage:82,
        one:require('../Assets/image/5.jpg'),
        two:require('../Assets/image/6.jpg'),
        three:require('../Assets/image/7.jpg'),
        four:require('../Assets/image/8.jpg'),
    },

    {
        image:require('../Assets/image/girl.png'),
        title:'هنر های عالی',
        text:'طراح گرافیک از این متن به عنوان عنصری از ترکیب بندی برای پر کردن صفحه و ارایه اولیه شکل ظاهری و کلی طرح سفارش گرفته شده استفاده می نماید، تا از نظر گرافیکی نشانگر چگونگی نوع و اندازه فونت و ظاهر متن باشد.',
        percentage:67,
        one:require('../Assets/image/9.jpg'),
        two:require('../Assets/image/10.jpg'),
        three:require('../Assets/image/11.jpg'),
        four:require('../Assets/image/12.jpg'),
    }
]